blogapp/urls.py
from django.urls import path
from .views import *
app_name="blogapp"
urlpatterns=[
path('',HomeView.as_view(),name='home'),
path('about/',AboutView.as_view(),name='about'),
path('contact/',ContactView.as_view(),name='contact'),
path('nepal/',NepalView.as_view(),name='nepal'),
path('blog/list/',BlogListView.as_view(),name='bloglist'),
path("blog/<int:pk>/detail/",BlogDetailView.as_view(),name='blogdetail'),
path('news/list/',NewsListView.as_view(),name='newslist'),
path("news/<int:pk>/detail/",NewsDetailView.as_view(),name='newsdetail'),
path("blog/create/",BlogCreateView.as_view(),name='blogcreate'),
path("blog/<int:pk>/update/",BlogUpdateView.as_view(),name='updateview'),
path("blog/<int:pk>/delete/",BlogDeleteView.as_view(),name='deleteview'),
path('news/create/',NewsCreateView.as_view(),name='newscreate'),
path('news/<int:pk>/update/',NewsUpdateView.as_view(),name='nupdateview'),
path('news/<int:pk>/delete/',NewsDeleteView.as_view(),name='ndeleteview'),
path('login/',LoginView.as_view(),name='login'),
path('logout/',LogoutView.as_view(),name='logout'),
path('category/<int:pk>/',CategoryDetailView.as_view(),name='categorydetail'),
path('userform/',UserRegisterForm.as_view(),name='userforms'),

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blogapp.urls")),
    ]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
class Blog(models.Model):
	title = models.CharField(max_length=200)
	image = models.ImageField(upload_to="blogs")
	content = models.TextField()
	author = models.CharField(max_length=100)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title+"("+self.author+")"+str(self.date)

class Event(models.Model):
	name = models.CharField(max_length=100)
	content = models.TextField()
	composed = models.CharField(max_length=100)
	etype = models.CharField(max_length=100)
	edate = models.DateField()

	def __str__(self):
		return self.composed + " " + str(self.edate)

class Category(models.Model):
	title=models.CharField(max_length=200)
	image=models.ImageField(upload_to='category')

	def __str__(self):
		return self.title
class News(models.Model):
	title=models.CharField(max_length=200)
	category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='relatednews')
	# category=models.ManyToManyField(Category)
	image=models.ImageField(upload_to='news')
	detail=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	author=models.CharField(max_length=100,null=True,blank=True)

	def __str__(self):
		return self.title

class Message(models.Model):
	name=models.CharField(max_length=200)
	phone=models.CharField(max_length=200)
	email=models.EmailField(null=True,blank=True)
	message=models.CharField(max_length=100)
	subject=models.CharField(max_length=100)
	date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.name

blogapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class BlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields=['title','content','author','image']

class NewsForm(forms.ModelForm):
	class Meta:
		model=News
		fields=['title','category','image','detail','author']

class MessageForm(forms.Form):
	sender=forms.CharField(widget=forms.TextInput())
	mobile=forms.CharField(widget=forms.NumberInput())
	email=forms.CharField(widget=forms.EmailInput())
	subject=forms.CharField(widget=forms.TextInput())
	message=forms.CharField(widget=forms.Textarea())
			
class LoginForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	password=forms.CharField(widget=forms.PasswordInput())

class UserForm(forms.Form):
	username=forms.CharField(widget=forms.TextInput())
	email=forms.CharField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())
	def clean_confirm_password(self):
		password=self.cleaned_data.get('password')
		confirm_password=self.cleaned_data.get('confirm_password')
		if password != confirm_password:
			raise forms.ValidationError('password & confirm password didnot match')
		return confirm_password
	def clean_username(self):
		username=self.cleaned_data.get('username')
		users=User.objects.filter(username=username)
		if users.exists():
			raise forms.ValidationError('username is  already created')
		return username
		i

blogapp/views.py
from django.views.generic import *
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

# Create your views here.
class HomeView(TemplateView):
	template_name="home.html"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context['narendra']='i am narendra'
		context['blogs']=Blog.objects.all()
		context['events']=Event.objects.all()
		context['categorylist']=Category.objects.all()
		return context

class  AboutView(TemplateView):
	template_name='about.html'

class ContactView(FormView):
	template_name='contact.html' 
	form_class=MessageForm
	success_url="/"

	def form_valid(self,form):
		sender=form.cleaned_data["sender"]
		mobile=form.cleaned_data['mobile']
		email=form.cleaned_data['email']
		subject=form.cleaned_data['subject']
		message=form.cleaned_data['message']
		print(sender,mobile,email,subject,message)
		Message.objects.create(name=sender,phone=mobile,email=email,subject=subject,message=message)
		return super().form_valid(form)         

class NepalView(TemplateView):
	template_name='nepal.html'
		
class BlogListView(ListView):
	template_name='bloglist.html'
	queryset=Blog.objects.all()
	# model=Blog
	context_object_name='allblogs'

class EventListView(ListView):
	template_name='enventlist.html'
	queryset=Event.objects.all()
	# model=Blog
	context_object_name='allevents'

class BlogDetailView(DetailView):
	template_name='blogdetail.html'
	model=Blog
	context_object_name='blog'

class NewsListView(ListView):
	template_name='newslist.html'
	queryset=News.objects.all()
	context_object_name='allnews'

class NewsDetailView(DetailView):
	template_name="newsdetail.html" 
	model=News
	context_object_name='news'

class NewsCreateView(CreateView):
	template_name='newscreate.html'
	form_class=NewsForm
	success_url="/"

class NewsUpdateView(UpdateView):
	template_name='newscreate.html'
	form_class=NewsForm
	success_url='/news/list'
	model=News

class NewsDeleteView(DeleteView):
	template_name='newsdelete.html'
	model=News
	success_url="/news/list/"

class BlogCreateView(LoginRequiredMixin,CreateView):
	template_name='blogcreate.html'
	form_class=BlogForm
	success_url="/"
	login_url="/login/"

	def get_context_data(self,**kwargs):
		context=super().get_context_data(**kwargs)
		context['blogs']=Blog.objects.all()
		return context


	def form_valid(self,form):
		title=form.cleaned_data['title']
		print(title)
		return super().form_valid(form)  


class BlogUpdateView(LoginRequiredMixin,UpdateView):
	template_name='blogcreate.html'
	form_class=BlogForm
	success_url="/blog/list"
	model=Blog
	login_url="/login/"

class BlogDeleteView(LoginRequiredMixin,DeleteView):
	template_name="blogdelete.html"
	model=Blog
	success_url="/blog/list/"
	login_url="/login/"


class LoginView(FormView):
	template_name='login.html'
	form_class=LoginForm
	success_url="/"
	def form_valid(self,form):
		uname=form.cleaned_data['username']
		pword=form.cleaned_data['password']
		user=authenticate(username=uname,password=pword)
		if user is not None:
			login(self.request,user)
		else:
			return render(self.request,self.template_name,{'form':form,'error':"you are not authorized"})
		print(uname,pword,"-----------------")
		return super().form_valid(form)

class LogoutView(View):
	def get(self,request):
		logout(request)
		return redirect('/')

class CategoryDetailView(DetailView):
	template_name='categorydetail.html'
	model=Category
	context_object_name='category'
class UserRegisterForm(FormView):
	template_name='usercreate.html'
	form_class=UserForm
	success_url="/"
	def form_valid(self,form):
		username=form.cleaned_data['username']
		email=form.cleaned_data['email']
		password=form.cleaned_data['password']
		print(username)
		User.objects.create_user(username,email,password)
		return super().form_valid(form)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3>hello this is about page</h3>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="container">
<a href="/">Home</a>
<a href="/about/">About</a>
<a href="/contact/">Contact</a>
<a href="/nepal/">Nepal</a>
<a href="/blog/list/">BlogList</a>
<a href="/news/list/">NewsList</a>
<a href="/blog/create/">CreateForm</a>
<a href="/news/create/">NCreateForm</a>
<a href="/userform/">UserCreationForm</a>
{% if request.user.is_authenticated %}
<p class="text-info">{{request.user}}</p>
<a href="/logout/">Logout</a>

{% else %}
<a href="/login/">Login</a>
{% endif %}

{% block content %}
{% endblock %} 

</body>
</html>

templates/blogcreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h3>Add new blog</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button>Submit</button>

		</form>
	</div>
	<div class="col-md-6">
		<h3>latest blogs</h3>
		{% for blog in blogs %}
		{% for blog in blogs|slice:'5' %}
		{{blog.content|truncatechars:'100'}}
		<h4>{{blog.title}}</h4>
		<img src="{{blog.image.url}}" class="img-fluid">
		{% endfor %}
		{% endfor %}
		
	</div>
	


</div>
{% endblock %}

templates/blogdelete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST" action="/blog/{{object.id}}/delete/">
	{% csrf_token %}
	<h4>Delete {{object.title}}</h4>
	<button>Delete</button>
	<a href="/blog/list/">Cancel</a>
</form>
{% endblock %}

templates/blogdetail.html
{% extends 'base.html' %}

{% block content %}
	<h1>Welcome to blogdetail</h1>
	<h3>{{blog.title}}</h3>
	<a href="/blog/{{blog.id}}/update/">update</a>
	<a href="/blog/{{blog.id}}/delete/">delete</a>
	<img src="{{blog.image.url}}" width=200>
	<p>{{blog.content}}</p>
	<h3>{{blog.author}}
	
{% endblock %}

templates/categorydetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>welcome to categorydetail</h1>
<h3>Category:{{category.title}}</h3>
{% for news in category.relatednews.all %}
<li><a href="{% url 'blogapp:newsdetail' news.id %}">{{news.title}}</a></li>
{% endfor %}
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3>hello this is contact page</h3>
<form method='POST'>
{% csrf_token %}
{{form.as_p}}
<button>Submit data</button>
</form>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<hr>
{% for category in categorylist %}
<a href="{% url 'blogapp:categorydetail' category.id %}">{{category.title}}</a>|
{% endfor %}
<h3>hello this is home page</h3>
{{narendra}}
{% for blog in blogs %}
<li>{{blog.title}}
	{% endfor %}
</li>
{% for event in events %}
<ul>
	{{event.name}}
</ul>
{% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>LoginFORM</h3>
{% if error %}
<li class="text-danger">{{error}}</li>
{% endif %}
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>LOGIN</button>
</form>
{% endblock %}

templates/nepal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h3>nepal is one of the country</h3>
{% endblock %}

templates/newscreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<h3>Add new News</h3>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button>Submit</button>

		</form>
{% endblock %}

templates/newsdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<h1>Welcome to newsdetail</h1>
	<h3>{{news.title}}</h3>
	<h1>{{news.category.image.url}}</h1>
	<hr>
	<a href="/news/{{news.id}}/update/">update</a>
	<a href="/news/{{news.id}}/delete/">delete</a>
	<img src="{{news.image.url}}" width=200>
	<p>{{news.content}}</p>
	<h3>{{news.author}}</h3>
	<h3>categories</h3>
	<h5>{{news.category}}</h5>
	<br>
<h3>Related News</h3><hr>
<div class="row">
	{% for article in news.category.relatednews.all %}
	{% if article.id != news.id %}

	<div class="col-md-3">
		<h4><a href="{% url 'blogapp:newsdetail' article.id %}">{{article.title}}</a></h4>
		<img src="{{article.image.url}}" class="img-fluid">
	</div>
	{% endif %}
	{% endfor %}
</div>

{% endblock %}

templates/newslist.html
{% extends 'base.html' %}

{% block content %}
	<h1>Welcome to Newslist</h1>
	{% for news in allnews %}
		<h4><a href="/news/{{news.id}}/detail">{{news.title}}</a></h4>
		<p>{{news.author}}</p>
		<img src="{{news.image.url}}" width="200">
		<h3>categories</h3>
		{% for category in news.category.all %}
			<li>{{category.title}}</li>
		{% endfor %}
		<hr>
	{% endfor %}
{% endblock %}

templates/usercreate.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
		{% csrf_token %}
			{{form.as_p}}
			<button>Submit</button>
</form>
{% endblock %}